### ISSUE TITLE
Game does not exit after closing window

### ISSUE THREAD

**Issue by Lignumm** [Lemmmy/JRogue#12]
Bisect shows this started happening as of 577cdd22a028b397a42a3b56e9b4e965636e0f89.

EDIT: Bisect is wrong

**Comment by Lemmmy** [comment]
its something to do with saving on dispose, theres like 4 methods to exit the game that all act differently

**Comment by Lignumm** [comment]
After analysing it manually, it happens as of ac6c9383cf4b555deeefe06efbe100600b4014b3.

**Comment by Lemmmy** [comment]
what the heck?

**Comment by Lemmmy** [comment]
no, the cause is its parent commit, c5f52de

**Comment by Lignumm** [comment]
Nope,  removing `<OnStartupTriggeringPolicy />` does indeed fix it.

**Comment by Lemmmy** [comment]
hmm, however that is an important policy - otherwise we'd get 5mb logs being uploaded to this issue tracker. look in the log4j2 issues?

**Comment by Lignumm** [comment]
Seems like this is the solution: http://stackoverflow.com/questions/41292188/why-log4j2s-rollingfile-appender-prevents-a-stand-alone-application-to-terminat/41294584

**Comment by Lemmmy** [comment]
nice, PR that in
